@HotelListing.Api_HostAddress = https://localhost:7185


GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  //Country
}

###

GET {{HotelListing.Api_HostAddress}}/api/countries

###
